### ISSUE TITLE
Slimefun Items in game are not properly recognized by JEI, REI, or EMI

### ISSUE THREAD

**Issue by 54M44R** [JustAHuman-xD/SlimefunToEMI#25] opened 2024-03-22 05:45 UTC
There are notable issues when using the `R` keybind to view recipes. Depending on how the keybind is used, the proper or vanilla recipe may be displayed. My speculation is that the issue is due to Slimefun Guide recipes not being registered as Slimefun Essentials recipes.

Recipes that are searched for within JEI, REC, ...etc are displayed properly when using the `R` keybind:
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/8c3c442a-10cb-4db0-9afe-74c4b5ee1dbc)
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/48c7a8f8-b27a-4a2a-b16c-9fd5dcf55878)

Attempting to view recipes from the Slimefun Guide with the `R` keybind results in vanilla recipes:
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/098f1bf3-2956-4906-8f64-10ba98c31c2c)
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/7c6b19f9-b77b-46d3-b850-5a7f76ba2a56)

Differences in registered recipes:
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/a943528b-3aa2-46e5-b3bd-5c407231a7d1)
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/afd83a65-d37f-4f1a-ac11-5e29c681f949)

**Comment by JustAHuman-xD** [comment] 2024-03-22 12:08
So I know you've tested and confirmed this on JEI, could you test and confirm for REI or EMI?

If not totally cool and I'll do it myself when I get time, but if you did that save me some time

**Comment by 54M44R** [comment] 2024-03-27 15:42
REI suffers the same issues, as well as an additional one. Any item registered by Slimefun Essentials cannot be bookmarked with the `A` keybind.

EMI suffers a similar issue where instead of displaying vanilla recipes, it does not show any recipe at all. There is an additional issue with the recipe tree. Vanilla recipes viewed in the recipe tree show the complete breakdown of items. Recipes registered by Slimefun Essentials do not break down the recipes.

Electric Smeltery 2 showing the items required to make it, lacking the additional recipes for the Motor, Power Crystal, etc.
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/062fd2f7-588a-424b-a088-29cb4b6207d1)

Dispenser recipe properly showing all the items required to make it. Lists the bow's components rather than just the bow.
![image](https://github.com/JustAHuman-xD/SlimefunEssentials/assets/26176694/2ed9ede4-1ecf-43a8-a9e7-2e9b1811449e)

**Comment by JustAHuman-xD** [comment] 2024-03-29 11:17
For the recipe tree issue, it's not a bug, you just have to select default recipes for it to choose, that's all

**Comment by JustAHuman-xD** [comment] 2024-03-29 11:18
And wdym instead of showing vanilla recipes it shows nothing at all

**Comment by 54M44R** [comment] 2024-03-30 18:12
> For the recipe tree issue, it's not a bug, you just have to select default recipes for it to choose, that's all

I was not aware of this. I can confirm that EMI's recipe tree is functioning fine.


> And wdym instead of showing vanilla recipes it shows nothing at all

Using the `R` keybind is meant to show you the recipe of said item through JEI / REI / EMI. If you use the `R` keybind on JEI or REI with a Slimefun item from the guide, it displays a vanilla recipe. EMI does not attempt to display any recipe.

There is a detail I missed entirely that I just found. It is not limited to just the Slimefun Guide.

Any Slimefun item viewable from within JEI / REI / EMI shows the proper recipe. Any inventory that is not part of JEI / REI / EMI either treats the Slimefun item as its vanilla counterpart and displays the vanilla recipe(s), or does not display any recipe at all.

**Comment by JustAHuman-xD** [comment] 2024-03-30 19:30
> Any Slimefun item viewable from within JEI / REI / EMI shows the proper recipe. Any inventory that is not part of JEI / REI / EMI either treats the Slimefun item as its vanilla counterpart and displays the vanilla recipe(s), or does not display any recipe at all.

I think I've figured out the cause, I believe its because of the CustomModelData, you can prove me wrong however, if the server you are playing on uses custom model data and you check the items that have a custom model, that should do it. However if the server you are testing this on does not, and it still isn't working, then I'm not sure. I'll work on a fix for it today and I'm also already working on support for custom model data so yeah 👍

**Comment by JustAHuman-xD** [comment] 2024-03-31 06:34
Looks like I was basically dead on the mark *ish*. That is the case for EMI however for JEI it's more complicated and I haven't looked into it for REI yet. I'm not sure how to fix it in jei (going to talk to the devs) as it's a comparison issue, it doesn't see the jtemstacks in game as slimefunitemstacks, what I handle everything as, and there isn't really a simple solution to fixing that. I've already tried various mixins and stuff but it only broke stuff further, much to my confusion lol

**Comment by JustAHuman-xD** [comment] 2024-04-08 19:14
Got the fix for jei, been trying to do REI but it's taking a bit

**Comment by JustAHuman-xD** [comment] 2024-04-12 13:57
With the latest changes and REI pushing out the fix, this is ready on the main branch! I'll close this once I make a release with the fixes in it

**Comment by JustAHuman-xD** [comment] 2024-08-27 02:44
Totally forgot to close this, can you confirm if this is fixed or not? In the latest release it should be

**Comment by JustAHuman-xD** [comment] 2024-09-24 18:35
Can confirm this is fixed in latest

**Closed as completed by JustAHuman-xD** 2024-09-24 18:35 UTC
Labels: Bug, Confirmed
